package com.example.oriedita_common.resources

/**
 * Константы для ресурсов Oriedita
 * Этот файл содержит все ключи ресурсов, используемые в приложении
 */
object ResourceConstants {
    
    // Common
    const val BACK = "back"
    const val CLOSE = "close"
    const val CANCEL = "cancel"
    const val OK = "ok"
    const val SAVE = "save"
    const val DELETE = "delete"
    
    // Tools
    const val TOOL_DRAW_CREASE_FREE = "tool_draw_crease_free"
    const val TOOL_MOVE_CREASE_PATTERN = "tool_move_crease_pattern"
    const val TOOL_LINE_SEGMENT_DELETE = "tool_line_segment_delete"
    const val TOOL_CHANGE_CREASE_TYPE = "tool_change_crease_type"
    const val TOOL_LENGTHEN_CREASE = "tool_lengthen_crease"
    const val TOOL_DRAW_POINT = "tool_draw_point"
    const val TOOL_DELETE_POINT = "tool_delete_point"
    const val TOOL_CIRCLE_DRAW = "tool_circle_draw"
    const val TOOL_CIRCLE_DRAW_THREE_POINT = "tool_circle_draw_three_point"
    const val TOOL_CIRCLE_DRAW_FREE = "tool_circle_draw_free"
    const val TOOL_PARALLEL_DRAW = "tool_parallel_draw"
    const val TOOL_PERPENDICULAR_DRAW = "tool_perpendicular_draw"
    const val TOOL_SYMMETRIC_DRAW = "tool_symmetric_draw"
    const val TOOL_DRAW_CREASE_RESTRICTED = "tool_draw_crease_restricted"
    const val TOOL_DRAW_CREASE_SYMMETRIC = "tool_draw_crease_symmetric"
    const val TOOL_DRAW_CREASE_ANGLE_RESTRICTED = "tool_draw_crease_angle_restricted"
    const val TOOL_ANGLE_SYSTEM = "tool_angle_system"
    const val TOOL_CREASE_SELECT = "tool_crease_select"
    const val TOOL_CREASE_UNSELECT = "tool_crease_unselect"
    const val TOOL_CREASE_MOVE = "tool_crease_move"
    const val TOOL_CREASE_COPY = "tool_crease_copy"
    const val TOOL_CREASE_MAKE_MOUNTAIN = "tool_crease_make_mountain"
    const val TOOL_CREASE_MAKE_VALLEY = "tool_crease_make_valley"
    const val TOOL_CREASE_MAKE_EDGE = "tool_crease_make_edge"
    const val TOOL_CREASE_MAKE_AUX = "tool_crease_make_aux"
    const val TOOL_CREASE_TOGGLE_MV = "tool_crease_toggle_mv"
    const val TOOL_CREASE_DELETE_OVERLAPPING = "tool_crease_delete_overlapping"
    const val TOOL_CREASE_DELETE_INTERSECTING = "tool_crease_delete_intersecting"
    const val TOOL_SELECT_POLYGON = "tool_select_polygon"
    const val TOOL_UNSELECT_POLYGON = "tool_unselect_polygon"
    const val TOOL_SELECT_LASSO = "tool_select_lasso"
    const val TOOL_UNSELECT_LASSO = "tool_unselect_lasso"
    const val TOOL_TEXT = "tool_text"
    const val TOOL_ADD_FOLDING_CONSTRAINT = "tool_add_folding_constraint"
    const val TOOL_AXIOM5 = "tool_axiom5"
    const val TOOL_AXIOM7 = "tool_axiom7"
    
    // Line Types
    const val LINE_TYPE_EDGE = "line_type_edge"
    const val LINE_TYPE_MOUNTAIN = "line_type_mountain"
    const val LINE_TYPE_VALLEY = "line_type_valley"
    const val LINE_TYPE_AUX = "line_type_aux"
    
    // Menu
    const val MENU_TOOLS = "menu_tools"
    const val MENU_LINE_TYPE = "menu_line_type"
    const val MENU_UNDO = "menu_undo"
    const val MENU_REDO = "menu_redo"
    const val MENU_NEW = "menu_new"
    const val MENU_OPEN = "menu_open"
    const val MENU_SAVE = "menu_save"
    const val MENU_SETTINGS = "menu_settings"
    
    // Settings
    const val SETTINGS_GRID = "settings_grid"
    const val SETTINGS_GRID_SHOW = "settings_grid_show"
    const val SETTINGS_GRID_SNAP = "settings_grid_snap"
    const val SETTINGS_GRID_SIZE = "settings_grid_size"
    const val SETTINGS_ANGLE_SNAP = "settings_angle_snap"
    const val SETTINGS_ANGLE_SNAP_ENABLED = "settings_angle_snap_enabled"
    const val SETTINGS_ANGLE_SNAP_VALUE = "settings_angle_snap_value"
    const val SETTINGS_LINE_WIDTH = "settings_line_width"
    const val SETTINGS_POINT_SIZE = "settings_point_size"
    const val SETTINGS_ZOOM = "settings_zoom"
    const val SETTINGS_ZOOM_IN = "settings_zoom_in"
    const val SETTINGS_ZOOM_OUT = "settings_zoom_out"
    const val SETTINGS_ZOOM_RESET = "settings_zoom_reset"
    
    // Icon names
    const val ICON_LINE_WIDTH_DECREASE = "icon_line_width_decrease"
    const val ICON_LINE_WIDTH_INCREASE = "icon_line_width_increase"
    const val ICON_POINT_SIZE_DECREASE = "icon_point_size_decrease"
    const val ICON_POINT_SIZE_INCREASE = "icon_point_size_increase"
    const val ICON_ANTI_ALIAS_TOGGLE = "icon_anti_alias_toggle"
    const val ICON_LINE_STYLE_CHANGE = "icon_line_style_change"
    const val ICON_DRAW_CREASE_FREE = "icon_draw_crease_free"
    const val ICON_DRAW_CREASE_RESTRICTED = "icon_draw_crease_restricted"
    const val ICON_VORONOI = "icon_voronoi"
    const val ICON_MAKE_FLAT_FOLDABLE = "icon_make_flat_foldable"
    const val ICON_LENGTHEN_CREASE = "icon_lengthen_crease"
    const val ICON_LENGTHEN_CREASE2 = "icon_lengthen_crease2"
    const val ICON_ANGLE_BISECTOR = "icon_angle_bisector"
    const val ICON_RABBIT_EAR = "icon_rabbit_ear"
    const val ICON_PERPENDICULAR_DRAW = "icon_perpendicular_draw"
    const val ICON_SYMMETRIC_DRAW = "icon_symmetric_draw"
    const val ICON_CONTINUOUS_SYMMETRIC_DRAW = "icon_continuous_symmetric_draw"
    const val ICON_PARALLEL_DRAW = "icon_parallel_draw"
    const val ICON_SET_PARALLEL_DRAW_WIDTH = "icon_set_parallel_draw_width"
    const val ICON_FOLDABLE_LINE_DRAW = "icon_foldable_line_draw"
    const val ICON_ALL_S_STEP_TO_ORISEN = "icon_all_s_step_to_orisen"
    const val ICON_FISH_BONE_DRAW = "icon_fish_bone_draw"
    const val ICON_DOUBLE_SYMMETRIC_DRAW = "icon_double_symmetric_draw"
    const val ICON_SENBUN_B_NYURYOKU = "icon_senbun_b_nyuryoku"
    const val ICON_REFLECT = "icon_reflect"
    const val ICON_SELECT = "icon_select"
    const val ICON_UNSELECT = "icon_unselect"
    const val ICON_SELECT_ALL = "icon_select_all"
    const val ICON_UNSELECT_ALL = "icon_unselect_all"
    const val ICON_MOVE = "icon_move"
    const val ICON_MOVE2P2P = "icon_move2p2p"
    const val ICON_COPY = "icon_copy"
    const val ICON_COPY2P2P = "icon_copy2p2p"
    const val ICON_DELETE_SELECTED_LINE_SEGMENT = "icon_delete_selected_line_segment"
    const val ICON_LINE_SEGMENT_DELETE = "icon_line_segment_delete"
    const val ICON_EDGE_LINE_SEGMENT_DELETE = "icon_edge_line_segment_delete"
    const val ICON_AUX_LIVE_LINE_SEGMENT_DELETE = "icon_aux_live_line_segment_delete"
    const val ICON_DEL_L_TYPE = "icon_del_l_type"
    const val ICON_TRIM_BRANCHES = "icon_trim_branches"
    const val ICON_TO_MOUNTAIN = "icon_to_mountain"
    const val ICON_TO_VALLEY = "icon_to_valley"
    const val ICON_TO_EDGE = "icon_to_edge"
    const val ICON_TO_AUX = "icon_to_aux"
    const val ICON_ZEN_YAMA_TANI_HENKAN = "icon_zen_yama_tani_henkan"
    const val ICON_SENBUN_HENKAN2 = "icon_senbun_henkan2"
    const val ICON_SENBUN_HENKAN = "icon_senbun_henkan"
    const val ICON_IN_L_COL_CHANGE = "icon_in_L_col_change"
    const val ICON_ON_L_COL_CHANGE = "icon_on_L_col_change"
    const val ICON_VERTEX_ADD = "icon_vertex_add"
    const val ICON_VERTEX_DELETE = "icon_vertex_delete"
    const val ICON_V_DEL_CC = "icon_v_del_cc"
    const val ICON_V_DEL_ALL = "icon_v_del_all"
    const val ICON_V_DEL_ALL_CC = "icon_v_del_all_cc"
    const val ICON_INPUT_DATA = "icon_input_data"
    const val ICON_DRAW_TWO_COLORED_CP = "icon_draw_two_colored_cp"
    const val ICON_SUITEI_01 = "icon_suitei_01"
    const val ICON_KOTEIMEN_SITEI = "icon_koteimen_sitei"
    const val ICON_SUITEI_02 = "icon_suitei_02"
    const val ICON_SUITEI_03 = "icon_suitei_03"
    const val ICON_COLORED_XRAY_DECREASE = "icon_colored_xray_decrease"
    const val ICON_COLORED_XRAY_INCREASE = "icon_colored_xray_increase"
    const val ICON_COL_RED = "icon_col_red"
    const val ICON_COL_BLUE = "icon_col_blue"
    const val ICON_COL_BLACK = "icon_col_black"
    const val ICON_COL_CYAN = "icon_col_cyan"
    const val ICON_LINE_SEGMENT_DIVISION_SET = "icon_line_segment_division_set"
    const val ICON_GRID_CONFIGURE = "icon_grid_configure"
    const val ICON_UNDO = "icon_undo"
    const val ICON_REDO = "icon_redo"
    const val ICON_SET_UNDO_COUNT = "icon_set_undo_count"
    const val ICON_CORRECT_CP_BEFORE_FOLDING = "icon_correct_cp_before_folding"
    const val ICON_SELECT_PERSISTENT = "icon_select_persistent"
    const val ICON_COLORED_XRAY = "icon_colored_xray"
    const val ICON_DRAW_DIAGONAL_GRIDLINES = "icon_draw_diagonal_gridlines"
    
    // Bottom Panel
    const val ICON_FOLD = "icon_fold"
    const val ICON_ANOTHER_SOLUTION = "icon_another_solution"
    const val ICON_FOLDED_FIGURE_FLIP = "icon_folded_figure_flip"
    const val ICON_SCALE = "icon_scale"
    const val ICON_DUPLICATE_FOLDED_MODEL = "icon_duplicate_folded_model"
    const val ICON_FOLDED_FIGURE_TOGGLE_ANTI_ALIAS = "icon_folded_figure_toggle_anti_alias"
    const val ICON_FOLDED_FIGURE_TOGGLE_SHADOW = "icon_folded_figure_toggle_shadow"
    const val ICON_FRONT_COLOR = "icon_front_color"
    const val ICON_BACK_COLOR = "icon_back_color"
    const val ICON_LINE_COLOR = "icon_line_color"
    const val ICON_HALT = "icon_halt"
    const val ICON_FOLDED_FIGURE_TRASH = "icon_folded_figure_trash"
    const val ICON_RESET = "icon_reset"
    const val ICON_ORIAGARI_SOUSA = "icon_oriagari_sousa"
    const val ICON_ORIAGARI_SOUSA_2 = "icon_oriagari_sousa_2"
    const val ICON_AS100 = "icon_As100"
    const val ICON_GO_TO_FOLDED_FIGURE = "icon_go_to_folded_figure"
    const val ICON_FOLDED_FIGURE_MOVE = "icon_folded_figure_move"
    const val ICON_FOLDED_FIGURE_UNDO = "icon_folded_figure_undo"
    const val ICON_FOLDED_FIGURE_REDO = "icon_folded_figure_redo"
    const val ICON_FOLDED_FIGURE_UNDO_COUNT = "icon_folded_figure_undo_count"
    const val ICON_ADD_COLOR_CONSTRAINT = "icon_add_color_constraint"
    
    // App
    const val APP_NAME = "app_name"
    
    // Navigation
    const val ICON_MEMORI_YOKO_IDOU = "icon_memori_yoko_idou"
    const val ICON_MEMORI_TATE_IDOU = "icon_memori_tate_idou"
    const val ICON_TENKAIZU_KAKUDAI = "icon_tenkaizu_kakudai"
    const val ICON_TENKAIZU_SYUKUSYOU = "icon_tenkaizu_syukusyou"
    const val ICON_ZEN_SYOKIKA = "icon_zen_syokika"
    const val ICON_TENKAIZU_IDIU = "icon_tenkaizu_idiu"
    const val ICON_TENKAIZU_M_KAITEN = "icon_tenkaizu_m_kaiten"
    const val ICON_TENKAIZU_P_KAITEN = "icon_tenkaizu_p_kaiten"
    
    // Additional tool names (hardcoded in EditorScreen.kt)
    const val TOOL_BACKGROUND_CHANGE_POSITION = "tool_background_change_position"
    const val TOOL_CHANGE_STANDARD_FACE = "tool_change_standard_face"
    const val TOOL_CIRCLE_CHANGE_COLOR = "tool_circle_change_color"
    const val TOOL_CIRCLE_DRAW_CONCENTRIC = "tool_circle_draw_concentric"
    const val TOOL_CIRCLE_DRAW_CONCENTRIC_SELECT = "tool_circle_draw_concentric_select"
    const val TOOL_CIRCLE_DRAW_INVERTED = "tool_circle_draw_inverted"
    const val TOOL_CIRCLE_DRAW_SEPARATE = "tool_circle_draw_separate"
    const val TOOL_SQUARE_BISECTOR = "tool_square_bisector"
    const val TOOL_INWARD = "tool_inward"
    const val TOOL_DRAW_CREASE_ANGLE_RESTRICTED3 = "tool_draw_crease_angle_restricted3"
    const val TOOL_LINE_SEGMENT_DIVISION = "tool_line_segment_division"
    const val TOOL_LINE_SEGMENT_RATIO_SET = "tool_line_segment_ratio_set"
    const val TOOL_POLYGON_SET_NO_CORNERS = "tool_polygon_set_no_corners"
    const val TOOL_FISH_BONE_DRAW = "tool_fish_bone_draw"
    const val TOOL_DOUBLE_SYMMETRIC_DRAW = "tool_double_symmetric_draw"
    const val TOOL_CREASES_ALTERNATE_MV = "tool_creases_alternate_mv"
    const val TOOL_DRAW_CREASE_ANGLE_RESTRICTED5 = "tool_draw_crease_angle_restricted5"
    const val TOOL_VERTEX_MAKE_ANGULARLY_FLAT_FOLDABLE = "tool_vertex_make_angularly_flat_foldable"
    const val TOOL_FOLDABLE_LINE_INPUT = "tool_foldable_line_input"
    const val TOOL_VERTEX_DELETE_ON_CREASE = "tool_vertex_delete_on_crease"
    const val TOOL_PARALLEL_DRAW_WIDTH = "tool_parallel_draw_width"
    const val TOOL_OPERATION_FRAME_CREATE = "tool_operation_frame_create"
    const val TOOL_VORONOI_CREATE = "tool_voronoi_create"
    const val TOOL_FLAT_FOLDABLE_CHECK = "tool_flat_foldable_check"
    const val TOOL_SELECT_LINE_INTERSECTING = "tool_select_line_intersecting"
    const val TOOL_UNSELECT_LINE_INTERSECTING = "tool_unselect_line_intersecting"
    const val TOOL_LENGTHEN_CREASE_SAME_COLOR = "tool_lengthen_crease_same_color"
    const val TOOL_FOLDABLE_LINE_DRAW = "tool_foldable_line_draw"
    const val TOOL_REPLACE_LINE_TYPE_SELECT = "tool_replace_line_type_select"
    const val TOOL_DELETE_LINE_TYPE_SELECT = "tool_delete_line_type_select"
    const val TOOL_MODIFY_CALCULATED_SHAPE = "tool_modify_calculated_shape"
    const val TOOL_MOVE_CALCULATED_SHAPE = "tool_move_calculated_shape"
    const val TOOL_CIRCLE_DRAW_TANGENT_LINE = "tool_circle_draw_tangent_line"
    const val TOOL_CIRCLE_DRAW_TWO_CONCENTRIC_SELECT = "tool_circle_draw_two_concentric_select"
    const val TOOL_CONTINUOUS_SYMMETRIC_DRAW = "tool_continuous_symmetric_draw"
    const val TOOL_CREASE_ADVANCE_TYPE = "tool_crease_advance_type"
    const val TOOL_CREASE_MAKE_MV = "tool_crease_make_mv"
    const val TOOL_UNKNOWN = "tool_unknown"
} 